# Generated by Django 5.0.3 on 2024-04-05 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinstackcapital', '0002_alter_myuser_misc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='drop_client',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='coinstackcapital.dropdetail'),
        ),
    ]
