# Generated by Django 5.0.3 on 2024-04-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinstackcapital', '0003_alter_myuser_drop_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='misc',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
