# Generated by Django 5.0.3 on 2024-04-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinstackcapital', '0004_alter_myuser_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Country of Origin'),
        ),
    ]
