# Generated by Django 5.0.3 on 2024-04-06 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinstackcapital', '0005_myuser_country_of_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('total_balance', models.CharField(max_length=100)),
                ('total_credit', models.CharField(max_length=100)),
                ('total_equity_worth', models.CharField(max_length=100)),
                ('total_deposits', models.CharField(max_length=100)),
                ('total_withdrawals', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
