# Generated by Django 5.0.3 on 2024-04-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinstackcapital', '0007_remove_myuser_drop_client_alter_account_user_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
