# Generated by Django 5.0.3 on 2024-04-09 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinstackcapital', '0008_requestlog_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='logs',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
